export const UPDATE_PAGE = "UPDATE_PAGE";

export const UPDATE_NUMBER_OF_DETAILS = "UPDATE_NUMBER_OF_DETAILS";

export const PAGE_DATA_REQUEST = "PAGE_DATA_REQUEST";
export const PAGE_DATA_SUCCESS = "PAGE_DATA_SUCCESS";
export const PAGE_DATA_FAILURE = "PAGE_DATA_FAILURE";
